### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace' / /isbnlib/dev/_fmt.py

### ISSUE THREAD

**Issue by aeirado** [xlcnd/isbntools#108]
Hi,
I received the error below when I ran a small example of python script to try the isbntools that I got from PyPI:

```
$ python isbn_tmsa_book.py A defesa dos interesses difusos em juízo : meio ambiente, consumidor, patrimônio cultural, patrimônio público e outros interesses
The ISBN of the most `spoken-about` book with this title is 

... and the book is:

Traceback (most recent call last):
  File "isbn_tmsa_book.py", line 12, in <module>
    print(registry.bibformatters['labels'](meta(isbn)))
  File "/Python/.virtualenvs/WorldCat_test/lib/python3.9/site-packages/isbnlib/registry.py", line 51, in <lambda>
    'labels': lambda x: _fmtbib('labels', x),
  File "/Python/.virtualenvs/WorldCat_test/lib/python3.9/site-packages/isbnlib/dev/_fmt.py", line 151, in _fmtbib
    _gen_proc(fmtname, canonical),
  File "/Python/.virtualenvs/WorldCat_test/lib/python3.9/site-packages/isbnlib/dev/_fmt.py", line 105, in _gen_proc
    canonical['Title'] = canonical.get('Title').replace('"', '')
AttributeError: 'NoneType' object has no attribute 'replace
```

**The Script:**
```
#!/usr/bin/env python
import sys
from isbntools.app import *

query = sys.argv[1].replace(' ', '+')
isbn = isbn_from_words(query)

print("The ISBN of the most `spoken-about` book with this title is %s" % isbn)
print("")
print("... and the book is:")
print("")
print(registry.bibformatters['labels'](meta(isbn)))
```

I appreciate any help.
Best regards,
André

**Comment by xlcnd** [comment]
Hi,

First of all, you should use as command, something like this:

```$ python isbn_tmsa_book.py "A defesa dos interesses difusos em juízo"```

The search text **must** be in quotes!

Second, use a `try - except` block to catch the exception (in case `meta(isbn)`in `None`):
```
try:
    print(registry.bibformatters['labels'](meta(isbn)))
except AttributeError:
    pass
```
I hope this answers your question.

**Comment by aeirado** [comment]
Hi, @xlcnd 
Thank you!
