### ISSUE TITLE
sys.stdout.isatty() fails in function "set_msconsole()" in file "_console.py"

### ISSUE THREAD

**Issue by hans-fritz-pommes** [xlcnd/isbntools#128]
```
Traceback (most recent call last):  File "C:\Users\HansFritzPommes\Documents\app.py", line xy, in <module>
    from isbntools.app import meta
  File "C:\Users\HansFritzPommes\AppData\Local\Programs\Python\Python312\Lib\site-packages\isbntools\app.py", line 32, in <module>
    from ._initapp import config, registry, CONF_PATH, CACHE_FILE
  File "C:\Users\HansFritzPommes\AppData\Local\Programs\Python\Python312\Lib\site-packages\isbntools\_initapp.py", line 174, in <module>
    set_msconsole()
  File "C:\Users\HansFritzPommes\AppData\Local\Programs\Python\Python312\Lib\site-packages\isbntools\_console.py", line 108, in set_msconsole
    if not sys.stdout.isatty():
AttributeError: 'NoneType' object has no attribute 'isatty'
```
I get this error when I use a program using isbntools compiled with cx-freeze.
I think, this error happens because `sys.stdout` is `None` in this case, because I use a cx-freeze so called `WIN32GUI` application, which drops all requests to sys.stdout.
My recommendation:
in file "_console.py":
in function `set_msconsole()`:
```
try:
    if not sys.stdout.isatty():
        return
except AttributeError:
    return
```

**Comment by hans-fritz-pommes** [comment]
I see `isbntools` is not thought for cx_freeze - use `isbnlib` instead
